const nodemailer = require('nodemailer');
const { env } = require('../config/env');
const logger = require('../utils/logger');

let transporter = null;

function getTransporter() {
  if (transporter) return transporter;

  if (!env.SMTP_HOST || !env.SMTP_USER) {
    logger.warn('⚠️ SMTP not configured. Emails will be logged to console.');
    return null;
  }

  transporter = nodemailer.createTransport({
    host: env.SMTP_HOST,
    port: env.SMTP_PORT,
    secure: env.SMTP_PORT === 465,
    auth: {
      user: env.SMTP_USER,
      pass: env.SMTP_PASS,
    },
  });

  return transporter;
}

async function sendEmail({ to, subject, html, text }) {
  const transport = getTransporter();

  if (!transport) {
    // Log to console in development
    logger.info('📧 [EMAIL - DEV MODE]', { to, subject, text: text?.substring(0, 100) });
    return { messageId: 'dev-mode', logged: true };
  }

  try {
    const info = await transport.sendMail({
      from: `"AI Content System" <${env.SMTP_FROM}>`,
      to,
      subject,
      html,
      text,
    });

    logger.info(`📧 Email sent: ${info.messageId}`, { to, subject });
    return info;
  } catch (err) {
    logger.error('Email send failed', { to, subject, error: err.message });
    // Don't throw — email failure shouldn't break the workflow
    return null;
  }
}

// ============================================
// Email Templates
// ============================================

async function notifyDraftReady({ draftId, submitterName, contentTitle }) {
  const dashboardUrl = `${env.FRONTEND_URL}/drafts/${draftId}`;

  return sendEmail({
    to: env.MARKETING_EMAIL,
    subject: `[AI Content] Draft #${draftId.slice(0, 8)} - Ready for Review`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 24px; border-radius: 8px 8px 0 0;">
          <h2 style="color: white; margin: 0;">🎯 New Draft Ready for Review</h2>
        </div>
        <div style="background: #f8f9fa; padding: 24px; border-radius: 0 0 8px 8px;">
          <p><strong>${submitterName}</strong> submitted: <em>"${contentTitle || 'Untitled'}"</em></p>
          <p>AI has generated LinkedIn, Twitter, and Instagram drafts.</p>
          <a href="${dashboardUrl}" style="display: inline-block; background: #667eea; color: white; padding: 12px 24px; border-radius: 6px; text-decoration: none; margin-top: 12px;">
            Review Draft →
          </a>
          <p style="color: #888; font-size: 12px; margin-top: 24px;">
            Generated by AI Marketing Automation System
          </p>
        </div>
      </div>
    `,
    text: `New Draft Ready: ${submitterName} submitted "${contentTitle}". Review at: ${dashboardUrl}`,
  });
}

async function notifySubmitter({ email, name, contentTitle, draftId, status }) {
  const statusEmoji = status === 'approved' ? '✅' : '❌';
  const statusText = status === 'approved' ? 'Approved' : 'Needs Changes';

  return sendEmail({
    to: email,
    subject: `[AI Content] Draft #${draftId.slice(0, 8)} - ${statusText}`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: ${status === 'approved' ? '#10b981' : '#ef4444'}; padding: 24px; border-radius: 8px 8px 0 0;">
          <h2 style="color: white; margin: 0;">${statusEmoji} Content ${statusText}</h2>
        </div>
        <div style="background: #f8f9fa; padding: 24px; border-radius: 0 0 8px 8px;">
          <p>Hi ${name},</p>
          <p>Your content submission <strong>"${contentTitle || 'Untitled'}"</strong> has been <strong>${status}</strong>.</p>
          ${status === 'rejected' ? '<p>Please check the feedback and resubmit if needed.</p>' : '<p>Your content will be scheduled for publishing.</p>'}
          <p style="color: #888; font-size: 12px; margin-top: 24px;">
            Generated by AI Marketing Automation System
          </p>
        </div>
      </div>
    `,
    text: `Hi ${name}, your content "${contentTitle}" has been ${status}.`,
  });
}

module.exports = { sendEmail, notifyDraftReady, notifySubmitter };
